apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: yashdubey455/bookmyshow:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
